baseURL = 'https://spr12ian.github.io/'
copyright = 'Ian Sweeney'
enableEmoji = true
languageCode = 'en-GB'
paginate = 100
sectionPagesMenu = 'main'
theme = "beautifulhugo"
title = 'My UK Gadgets & Me'


[params]
  mainSections = ["post","posts"]

