baseURL = 'https://spr12ian.github.io/'
copyright = 'Ian Sweeney'
enableEmoji = true
languageCode = 'en-GB'
paginate = 100
sectionPagesMenu = 'main'
theme = ["github.com/halogenica/beautifulhugo"]
title = 'My UK Gadgets & Me'
pygmentsUseClasses = true
pygmentsCodeFences = true

[module]
  [module.hugoVersion]
    extended = true
[[module.imports]]
  path = 'github.com/halogenica/beautifulhugo'

[params]
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowToc = true

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true