baseURL = 'https://spr12ian.github.io/'
languageCode = 'en-GB'
sectionPagesMenu = 'main'
theme = ["github.com/halogenica/beautifulhugo"]
title = 'My UK Gadgets & Me'

[params]

ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowToc = true